<?php
require_once __DIR__ . '/../../../includes/fpdf/fpdf.php';
require_once __DIR__ . '/../../../config/config.php';

// Require admin session
session_start();
if (!isset($_SESSION['admin_id'])) {
    die('Unauthorized access');
}

$type = isset($_GET['type']) ? $_GET['type'] : 'sales';
$startDate = isset($_GET['start']) ? $_GET['start'] : date('Y-m-01');
$endDate = isset($_GET['end']) ? $_GET['end'] : date('Y-m-d');
$groupBy = isset($_GET['group']) ? $_GET['group'] : 'month';

$reportTitles = [
    'sales' => 'SALES REPORT',
    'inventory' => 'INVENTORY REPORT',
    'customers' => 'CUSTOMER REPORT',
    'orders' => 'ORDERS REPORT',
    'financial' => 'FINANCIAL REPORT'
];

$reportTitle = $reportTitles[$type] ?? 'BUSINESS REPORT';

try {
    // Create PDF
    $pdf = new FPDF();
    $pdf->AddPage();

    // Header with logo
    $logoPath = __DIR__ . '/../../../assets/images/M&E_LOGO_transparent.png';
    if (file_exists($logoPath)) {
        $pdf->Image($logoPath, 10, 8, 20);
    }

    // Title
    $pdf->SetFont('Arial', 'B', 18);
    $pdf->SetTextColor(30, 64, 175);
    $pdf->Cell(0, 10, $reportTitle, 0, 1, 'C');
    
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Cell(0, 6, 'M&E: Interior Supplies Trading', 0, 1, 'C');
    
    $pdf->SetFont('Arial', '', 9);
    $pdf->SetTextColor(100, 100, 100);
    $pdf->Cell(0, 5, 'Report Period: ' . date('M d, Y', strtotime($startDate)) . ' - ' . date('M d, Y', strtotime($endDate)), 0, 1, 'C');
    $pdf->Cell(0, 5, 'Generated on: ' . date('F j, Y g:i A'), 0, 1, 'C');
    $pdf->Ln(5);

    // Divider
    $pdf->SetDrawColor(30, 64, 175);
    $pdf->SetLineWidth(0.5);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(8);

    // Generate report based on type
    switch ($type) {
        case 'sales':
            generateSalesPDF($pdf, $pdo, $startDate, $endDate);
            break;
        case 'inventory':
            generateInventoryPDF($pdf, $pdo);
            break;
        case 'customers':
            generateCustomersPDF($pdf, $pdo, $startDate, $endDate);
            break;
        case 'orders':
            generateOrdersPDF($pdf, $pdo, $startDate, $endDate);
            break;
        case 'financial':
            generateFinancialPDF($pdf, $pdo, $startDate, $endDate);
            break;
    }

    // Footer
    $pdf->SetY(-20);
    $pdf->SetDrawColor(200, 200, 200);
    $pdf->Line(10, $pdf->GetY(), 200, $pdf->GetY());
    $pdf->Ln(3);
    
    $pdf->SetFont('Arial', 'I', 8);
    $pdf->SetTextColor(100, 100, 100);
    $pdf->Cell(0, 4, 'M&E Interior Supplies Trading - Business Intelligence Report', 0, 1, 'C');
    $pdf->Cell(0, 4, 'Generated by: ' . ($_SESSION['admin_username'] ?? 'Admin'), 0, 1, 'C');

    // Output PDF
    $filename = str_replace(' ', '_', $reportTitle) . '_' . date('Y-m-d') . '.pdf';
    $pdf->Output('D', $filename);

} catch (Exception $e) {
    die('Error generating report: ' . $e->getMessage());
}

function generateSalesPDF($pdf, $pdo, $startDate, $endDate) {
    // Summary
    $summarySql = "SELECT 
                    COUNT(DISTINCT order_id) as total_orders,
                    SUM(final_amount) as total_revenue,
                    AVG(final_amount) as average_order_value,
                    COUNT(DISTINCT user_id) as unique_customers
                   FROM orders
                   WHERE order_date BETWEEN :start AND :end
                   AND order_status != 'Cancelled'";
    $summaryStmt = $pdo->prepare($summarySql);
    $summaryStmt->execute([':start' => $startDate, ':end' => $endDate]);
    $summary = $summaryStmt->fetch(PDO::FETCH_ASSOC);

    // Summary Section
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(30, 64, 175);
    $pdf->Cell(0, 7, 'Sales Summary', 0, 1);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFont('Arial', '', 10);

    $pdf->SetFillColor(240, 248, 255);
    $pdf->Cell(95, 7, 'Total Orders:', 1, 0, 'L', true);
    $pdf->Cell(95, 7, number_format($summary['total_orders']), 1, 1, 'R', true);
    
    $pdf->Cell(95, 7, 'Total Revenue:', 1, 0, 'L');
    $pdf->Cell(95, 7, 'PHP ' . number_format($summary['total_revenue'], 2), 1, 1, 'R');
    
    $pdf->Cell(95, 7, 'Average Order Value:', 1, 0, 'L', true);
    $pdf->Cell(95, 7, 'PHP ' . number_format($summary['average_order_value'], 2), 1, 1, 'R', true);
    
    $pdf->Cell(95, 7, 'Unique Customers:', 1, 0, 'L');
    $pdf->Cell(95, 7, number_format($summary['unique_customers']), 1, 1, 'R');
    
    $pdf->Ln(8);

    // Top Products
    $topProductsSql = "SELECT p.product_name, SUM(oi.quantity) as total_sold, SUM(oi.subtotal) as revenue
                       FROM order_items oi
                       INNER JOIN orders o ON o.order_id = oi.order_id
                       INNER JOIN products p ON p.product_id = oi.product_id
                       WHERE o.order_date BETWEEN :start AND :end
                       AND o.order_status != 'Cancelled'
                       GROUP BY p.product_id, p.product_name
                       ORDER BY total_sold DESC
                       LIMIT 15";
    $topProductsStmt = $pdo->prepare($topProductsSql);
    $topProductsStmt->execute([':start' => $startDate, ':end' => $endDate]);
    $topProducts = $topProductsStmt->fetchAll(PDO::FETCH_ASSOC);

    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(30, 64, 175);
    $pdf->Cell(0, 7, 'Top Selling Products', 0, 1);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Ln(2);

    // Table Header
    $pdf->SetFillColor(30, 64, 175);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->SetFont('Arial', 'B', 9);
    $pdf->Cell(100, 7, 'Product Name', 1, 0, 'L', true);
    $pdf->Cell(40, 7, 'Units Sold', 1, 0, 'C', true);
    $pdf->Cell(40, 7, 'Revenue', 1, 1, 'R', true);

    // Table Rows
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFont('Arial', '', 9);
    $rowCount = 0;

    foreach ($topProducts as $product) {
        $fill = ($rowCount % 2 == 0);
        if ($fill) $pdf->SetFillColor(248, 250, 252);
        
        $productName = strlen($product['product_name']) > 50 ? 
                      substr($product['product_name'], 0, 47) . '...' : 
                      $product['product_name'];
        
        $pdf->Cell(100, 6, $productName, 1, 0, 'L', $fill);
        $pdf->Cell(40, 6, number_format($product['total_sold']), 1, 0, 'C', $fill);
        $pdf->Cell(40, 6, number_format($product['revenue'], 2), 1, 1, 'R', $fill);
        $rowCount++;
    }
}

function generateInventoryPDF($pdf, $pdo) {
    // Summary
    $summarySql = "SELECT 
                    COUNT(*) as total_products,
                    SUM(stock_quantity) as total_stock,
                    SUM(stock_quantity * price) as total_value,
                    SUM(CASE WHEN stock_quantity = 0 THEN 1 ELSE 0 END) as out_of_stock,
                    SUM(CASE WHEN stock_quantity <= COALESCE(NULLIF(min_stock_level, 0), 15) THEN 1 ELSE 0 END) as low_stock
                   FROM products
                   WHERE isActive = 1";
    $summaryStmt = $pdo->query($summarySql);
    $summary = $summaryStmt->fetch(PDO::FETCH_ASSOC);

    // Summary Section
    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(30, 64, 175);
    $pdf->Cell(0, 7, 'Inventory Summary', 0, 1);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFont('Arial', '', 10);

    $pdf->SetFillColor(240, 248, 255);
    $pdf->Cell(95, 7, 'Total Products:', 1, 0, 'L', true);
    $pdf->Cell(95, 7, number_format($summary['total_products']), 1, 1, 'R', true);
    
    $pdf->Cell(95, 7, 'Total Stock Units:', 1, 0, 'L');
    $pdf->Cell(95, 7, number_format($summary['total_stock']), 1, 1, 'R');
    
    $pdf->Cell(95, 7, 'Total Inventory Value:', 1, 0, 'L', true);
    $pdf->Cell(95, 7, 'PHP ' . number_format($summary['total_value'], 2), 1, 1, 'R', true);
    
    $pdf->Cell(95, 7, 'Out of Stock Items:', 1, 0, 'L');
    $pdf->SetTextColor(220, 38, 38);
    $pdf->Cell(95, 7, number_format($summary['out_of_stock']), 1, 1, 'R');
    
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Cell(95, 7, 'Low Stock Items:', 1, 0, 'L', true);
    $pdf->SetTextColor(245, 158, 11);
    $pdf->Cell(95, 7, number_format($summary['low_stock']), 1, 1, 'R', true);
    
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Ln(8);

    // Category breakdown
    $categorySql = "SELECT c.category_name, COUNT(*) as product_count, 
                           SUM(p.stock_quantity) as total_stock,
                           SUM(p.stock_quantity * p.price) as category_value
                    FROM products p
                    INNER JOIN categories c ON c.category_id = p.category_id
                    WHERE p.isActive = 1
                    GROUP BY c.category_id, c.category_name
                    ORDER BY category_value DESC";
    $categoryStmt = $pdo->query($categorySql);
    $categories = $categoryStmt->fetchAll(PDO::FETCH_ASSOC);

    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(30, 64, 175);
    $pdf->Cell(0, 7, 'Inventory by Category', 0, 1);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Ln(2);

    // Table Header
    $pdf->SetFillColor(30, 64, 175);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->SetFont('Arial', 'B', 9);
    $pdf->Cell(70, 7, 'Category', 1, 0, 'L', true);
    $pdf->Cell(35, 7, 'Products', 1, 0, 'C', true);
    $pdf->Cell(35, 7, 'Stock Units', 1, 0, 'C', true);
    $pdf->Cell(40, 7, 'Total Value', 1, 1, 'R', true);

    // Table Rows
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFont('Arial', '', 9);
    $rowCount = 0;

    foreach ($categories as $category) {
        $fill = ($rowCount % 2 == 0);
        if ($fill) $pdf->SetFillColor(248, 250, 252);
        
        $pdf->Cell(70, 6, $category['category_name'], 1, 0, 'L', $fill);
        $pdf->Cell(35, 6, number_format($category['product_count']), 1, 0, 'C', $fill);
        $pdf->Cell(35, 6, number_format($category['total_stock']), 1, 0, 'C', $fill);
        $pdf->Cell(40, 6, number_format($category['category_value'], 2), 1, 1, 'R', $fill);
        $rowCount++;
    }
}

function generateCustomersPDF($pdf, $pdo, $startDate, $endDate) {
    // Summary
    $summarySql = "SELECT 
                    COUNT(*) as total_customers,
                    SUM(CASE WHEN created_at BETWEEN :start AND :end THEN 1 ELSE 0 END) as new_customers
                   FROM users
                   WHERE isActive = 1";
    $summaryStmt = $pdo->prepare($summarySql);
    $summaryStmt->execute([':start' => $startDate, ':end' => $endDate]);
    $summary = $summaryStmt->fetch(PDO::FETCH_ASSOC);

    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(30, 64, 175);
    $pdf->Cell(0, 7, 'Customer Summary', 0, 1);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFont('Arial', '', 10);

    $pdf->SetFillColor(240, 248, 255);
    $pdf->Cell(95, 7, 'Total Customers:', 1, 0, 'L', true);
    $pdf->Cell(95, 7, number_format($summary['total_customers']), 1, 1, 'R', true);
    
    $pdf->Cell(95, 7, 'New Customers (Period):', 1, 0, 'L');
    $pdf->Cell(95, 7, number_format($summary['new_customers']), 1, 1, 'R');
    
    $pdf->Ln(8);

    // Top customers
    $topCustomersSql = "SELECT 
                         CONCAT(u.first_name, ' ', u.last_name) as customer_name,
                         COUNT(o.order_id) as total_orders,
                         SUM(o.final_amount) as total_spent
                        FROM users u
                        INNER JOIN orders o ON o.user_id = u.user_id
                        WHERE o.order_date BETWEEN :start AND :end
                        AND o.order_status != 'Cancelled'
                        GROUP BY u.user_id, customer_name
                        ORDER BY total_spent DESC
                        LIMIT 15";
    $topCustomersStmt = $pdo->prepare($topCustomersSql);
    $topCustomersStmt->execute([':start' => $startDate, ':end' => $endDate]);
    $topCustomers = $topCustomersStmt->fetchAll(PDO::FETCH_ASSOC);

    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(30, 64, 175);
    $pdf->Cell(0, 7, 'Top Customers', 0, 1);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Ln(2);

    $pdf->SetFillColor(30, 64, 175);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->SetFont('Arial', 'B', 9);
    $pdf->Cell(100, 7, 'Customer Name', 1, 0, 'L', true);
    $pdf->Cell(40, 7, 'Total Orders', 1, 0, 'C', true);
    $pdf->Cell(40, 7, 'Total Spent', 1, 1, 'R', true);

    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFont('Arial', '', 9);
    $rowCount = 0;

    foreach ($topCustomers as $customer) {
        $fill = ($rowCount % 2 == 0);
        if ($fill) $pdf->SetFillColor(248, 250, 252);
        
        $pdf->Cell(100, 6, $customer['customer_name'], 1, 0, 'L', $fill);
        $pdf->Cell(40, 6, number_format($customer['total_orders']), 1, 0, 'C', $fill);
        $pdf->Cell(40, 6, number_format($customer['total_spent'], 2), 1, 1, 'R', $fill);
        $rowCount++;
    }
}

function generateOrdersPDF($pdf, $pdo, $startDate, $endDate) {
    $summarySql = "SELECT 
                    COUNT(*) as total_orders,
                    SUM(CASE WHEN order_status = 'Delivered' THEN 1 ELSE 0 END) as delivered,
                    SUM(CASE WHEN order_status = 'Pending' THEN 1 ELSE 0 END) as pending,
                    SUM(CASE WHEN order_status = 'Cancelled' THEN 1 ELSE 0 END) as cancelled
                   FROM orders
                   WHERE order_date BETWEEN :start AND :end";
    $summaryStmt = $pdo->prepare($summarySql);
    $summaryStmt->execute([':start' => $startDate, ':end' => $endDate]);
    $summary = $summaryStmt->fetch(PDO::FETCH_ASSOC);

    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(30, 64, 175);
    $pdf->Cell(0, 7, 'Orders Summary', 0, 1);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFont('Arial', '', 10);

    $pdf->SetFillColor(240, 248, 255);
    $pdf->Cell(95, 7, 'Total Orders:', 1, 0, 'L', true);
    $pdf->Cell(95, 7, number_format($summary['total_orders']), 1, 1, 'R', true);
    
    $pdf->Cell(95, 7, 'Delivered Orders:', 1, 0, 'L');
    $pdf->SetTextColor(34, 197, 94);
    $pdf->Cell(95, 7, number_format($summary['delivered']), 1, 1, 'R');
    
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Cell(95, 7, 'Pending Orders:', 1, 0, 'L', true);
    $pdf->SetTextColor(245, 158, 11);
    $pdf->Cell(95, 7, number_format($summary['pending']), 1, 1, 'R', true);
    
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Cell(95, 7, 'Cancelled Orders:', 1, 0, 'L');
    $pdf->SetTextColor(220, 38, 38);
    $pdf->Cell(95, 7, number_format($summary['cancelled']), 1, 1, 'R');
    
    $pdf->SetTextColor(0, 0, 0);
}

function generateFinancialPDF($pdf, $pdo, $startDate, $endDate) {
    $summarySql = "SELECT 
                    SUM(final_amount) as total_revenue,
                    SUM(shipping_fee) as shipping_revenue,
                    SUM(total_amount) as product_revenue
                   FROM orders
                   WHERE order_date BETWEEN :start AND :end
                   AND order_status != 'Cancelled'";
    $summaryStmt = $pdo->prepare($summarySql);
    $summaryStmt->execute([':start' => $startDate, ':end' => $endDate]);
    $summary = $summaryStmt->fetch(PDO::FETCH_ASSOC);

    $pdf->SetFont('Arial', 'B', 12);
    $pdf->SetTextColor(30, 64, 175);
    $pdf->Cell(0, 7, 'Financial Summary', 0, 1);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->SetFont('Arial', '', 10);

    $pdf->SetFillColor(240, 248, 255);
    $pdf->Cell(95, 7, 'Total Revenue:', 1, 0, 'L', true);
    $pdf->Cell(95, 7, 'PHP ' . number_format($summary['total_revenue'], 2), 1, 1, 'R', true);
    
    $pdf->Cell(95, 7, 'Product Sales:', 1, 0, 'L');
    $pdf->Cell(95, 7, 'PHP ' . number_format($summary['product_revenue'], 2), 1, 1, 'R');
    
    $pdf->Cell(95, 7, 'Shipping Fees:', 1, 0, 'L', true);
    $pdf->Cell(95, 7, 'PHP ' . number_format($summary['shipping_revenue'], 2), 1, 1, 'R', true);
}
