// --- INVENTORY DATA ---
const inventoryData = [
    {
        id: 1,
        name: 'Ballpoint Pens',
        description: 'Pack of 12',
        category: 'office',
        categoryName: 'Office Supplies',
        sku: 'OFF-PEN-001',
        stock: 150,
        minStock: 20,
        price: 180,
        icon: '🖊️',
        stockLevel: 'high'
    },
    {
        id: 2,
        name: 'Bond Paper',
        description: 'A4 Ream 500 sheets',
        category: 'office',
        categoryName: 'Office Supplies',
        sku: 'OFF-PAP-002',
        stock: 85,
        minStock: 30,
        price: 250,
        icon: '📄',
        stockLevel: 'medium'
    },
    {
        id: 3,
        name: 'File Folders',
        description: 'Manila folders',
        category: 'office',
        categoryName: 'Office Supplies',
        sku: 'OFF-FOL-003',
        stock: 45,
        minStock: 15,
        price: 120,
        icon: '📁',
        stockLevel: 'medium'
    },
    {
        id: 4,
        name: 'Staplers',
        description: 'Heavy duty stapler',
        category: 'office',
        categoryName: 'Office Supplies',
        sku: 'OFF-STA-004',
        stock: 12,
        minStock: 25,
        price: 850,
        icon: '📎',
        stockLevel: 'low'
    },
    {
        id: 5,
        name: 'Notebooks',
        description: 'Spiral notebook 100 pages',
        category: 'school',
        categoryName: 'School Supplies',
        sku: 'SCH-NOT-005',
        stock: 8,
        minStock: 20,
        price: 65,
        icon: '📓',
        stockLevel: 'low'
    },
    {
        id: 6,
        name: 'Hand Sanitizer',
        description: '500ml bottle',
        category: 'sanitary',
        categoryName: 'Sanitary Supplies',
        sku: 'SAN-HAN-006',
        stock: 25,
        minStock: 30,
        price: 185,
        icon: '🧴',
        stockLevel: 'low'
    },
    {
        id: 7,
        name: 'Whiteboard Markers',
        description: 'Set of 4 colors',
        category: 'office',
        categoryName: 'Office Supplies',
        sku: 'OFF-MAR-007',
        stock: 75,
        minStock: 25,
        price: 320,
        icon: '🖍️',
        stockLevel: 'high'
    },
    {
        id: 8,
        name: 'Tissue Paper',
        description: 'Box of 200 sheets',
        category: 'sanitary',
        categoryName: 'Sanitary Supplies',
        sku: 'SAN-TIS-008',
        stock: 22,
        minStock: 40,
        price: 95,
        icon: '🧻',
        stockLevel: 'low'
    }
];

// --- LOW STOCK ALERTS DATA ---
const lowStockData = [
    {
        id: 1,
        name: 'Staplers',
        category: 'office',
        sku: 'OFF-STA-004',
        currentStock: 0,
        minStock: 25,
        icon: '📎',
        alertLevel: 'critical',
        daysSupply: 0,
        lastRestock: '2024-10-15',
        avgDailyUsage: 2.5
    },
    {
        id: 2,
        name: 'Notebooks',
        category: 'school',
        sku: 'SCH-NOT-005',
        currentStock: 8,
        minStock: 20,
        icon: '📓',
        alertLevel: 'critical',
        daysSupply: 3,
        lastRestock: '2024-10-20',
        avgDailyUsage: 2.8
    },
    {
        id: 3,
        name: 'Hand Sanitizer',
        category: 'sanitary',
        sku: 'SAN-HAN-006',
        currentStock: 5,
        minStock: 30,
        icon: '🧴',
        alertLevel: 'critical',
        daysSupply: 2,
        lastRestock: '2024-10-18',
        avgDailyUsage: 3.2
    },
    {
        id: 4,
        name: 'File Folders',
        category: 'office',
        sku: 'OFF-FOL-003',
        currentStock: 12,
        minStock: 15,
        icon: '📁',
        alertLevel: 'warning',
        daysSupply: 8,
        lastRestock: '2024-11-01',
        avgDailyUsage: 1.5
    },
    {
        id: 5,
        name: 'Whiteboard Markers',
        category: 'office',
        sku: 'OFF-MAR-007',
        currentStock: 18,
        minStock: 25,
        icon: '🖊️',
        alertLevel: 'warning',
        daysSupply: 12,
        lastRestock: '2024-10-28',
        avgDailyUsage: 1.8
    },
    {
        id: 6,
        name: 'Tissue Paper',
        category: 'sanitary',
        sku: 'SAN-TIS-008',
        currentStock: 22,
        minStock: 40,
        icon: '🧻',
        alertLevel: 'warning',
        daysSupply: 7,
        lastRestock: '2024-10-25',
        avgDailyUsage: 3.5
    },
    {
        id: 7,
        name: 'Printer Paper',
        category: 'office',
        sku: 'OFF-PAP-009',
        currentStock: 15,
        minStock: 20,
        icon: '📄',
        alertLevel: 'warning',
        daysSupply: 10,
        lastRestock: '2024-11-05',
        avgDailyUsage: 1.8
    },
    {
        id: 8,
        name: 'Calculators',
        category: 'office',
        sku: 'OFF-CAL-010',
        currentStock: 6,
        minStock: 10,
        icon: '🔢',
        alertLevel: 'warning',
        daysSupply: 15,
        lastRestock: '2024-10-12',
        avgDailyUsage: 0.4
    }
];

// --- STOCK MOVEMENTS DATA ---
const stockMovementsData = [
    {
        id: 1,
        productId: 1,
        productName: 'Ballpoint Pens',
        productSKU: 'OFF-PEN-001',
        type: 'add',
        quantity: 50,
        previousStock: 100,
        newStock: 150,
        reason: 'New Delivery',
        user: 'Admin',
        timestamp: '2024-11-15 10:30 AM'
    },
    {
        id: 2,
        productId: 2,
        productName: 'Bond Paper',
        productSKU: 'OFF-PAP-002',
        type: 'remove',
        quantity: 15,
        previousStock: 100,
        newStock: 85,
        reason: 'Sale',
        user: 'User1',
        timestamp: '2024-11-15 09:15 AM'
    },
    {
        id: 3,
        productId: 4,
        productName: 'Staplers',
        productSKU: 'OFF-STA-004',
        type: 'adjust',
        quantity: 4,
        previousStock: 8,
        newStock: 12,
        reason: 'Recount',
        user: 'Admin',
        timestamp: '2024-11-14 02:45 PM'
    },
    {
        id: 4,
        productId: 1,
        productName: 'Ballpoint Pens',
        productSKU: 'OFF-PEN-001',
        type: 'remove',
        quantity: 20,
        previousStock: 150,
        newStock: 130,
        reason: 'Sale',
        user: 'User2',
        timestamp: '2024-11-14 11:00 AM'
    },
    {
        id: 5,
        productId: 3,
        productName: 'File Folders',
        productSKU: 'OFF-FOL-003',
        type: 'add',
        quantity: 30,
        previousStock: 15,
        newStock: 45,
        reason: 'New Delivery',
        user: 'Admin',
        timestamp: '2024-11-13 04:00 PM'
    },
    {
        id: 6,
        productId: 5,
        productName: 'Notebooks',
        productSKU: 'SCH-NOT-005',
        type: 'remove',
        quantity: 12,
        previousStock: 20,
        newStock: 8,
        reason: 'Sale',
        user: 'User1',
        timestamp: '2024-11-13 01:30 PM'
    },
    {
        id: 7,
        productId: 6,
        productName: 'Hand Sanitizer',
        productSKU: 'SAN-HAN-006',
        type: 'remove',
        quantity: 5,
        previousStock: 30,
        newStock: 25,
        reason: 'Damaged',
        user: 'Admin',
        timestamp: '2024-11-12 10:00 AM'
    },
    {
        id: 8,
        productId: 7,
        productName: 'Whiteboard Markers',
        productSKU: 'OFF-MAR-007',
        type: 'add',
        quantity: 25,
        previousStock: 50,
        newStock: 75,
        reason: 'New Delivery',
        user: 'Admin',
        timestamp: '2024-11-11 03:00 PM'
    },
    {
        id: 9,
        productId: 8,
        productName: 'Tissue Paper',
        productSKU: 'SAN-TIS-008',
        type: 'remove',
        quantity: 18,
        previousStock: 40,
        newStock: 22,
        reason: 'Sale',
        user: 'User2',
        timestamp: '2024-11-10 09:00 AM'
    }
];
